# Generated by Django 5.2 on 2025-05-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('student_class', models.IntegerField()),
                ('photo', models.ImageField(default='images/default.webp', upload_to='images/')),
                ('video', models.FileField(default='videos/default.mp4', upload_to='videos/')),
            ],
        ),
    ]
